### ISSUE TITLE
Fails to convert GIFs

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [sverrirs/jekyll-webp#11]
Steps to reproduce:

1. Create a GIF in a directory currently being processed by the gem.
2. Add `".gif"` to the list of file formats.
3. Specify `."gif"` as the gif extension.
4. Observe the following error:

```
 Conversion for image someImage.gif failed, no webp version could be created for this image
```

Here's my config:

```yml
webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/img/"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpg", ".png", ".gif"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: true

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil
```

All other file formats work.
